apiVersion: v1
kind: Service
metadata:
  name: system-info-api-service
  labels:
    app: system-info-api
spec:
  type: NodePort
  selector:
    app: system-info-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 6000
      nodePort: 30080