apiVersion: v2
name: system-info-api
description: System Information API Helm Chart
type: application
version: 0.1.0
appVersion: "2.0.0"
keywords:
  - python
  - flask
  - api
maintainers:
  - name: PrizrakZamkov
    email: prizrakzamkov@gmail.com
sources:
  - https://github.com/PrizrakZamkov/DevOps-Core-Course-Prizrak
