# Default values for system-info-api

replicaCount: 3

image:
  repository: prizrakzamkov/system-info-api
  pullPolicy: Always
  tag: "latest"

nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 80
  targetPort: 6000
  nodePort: 30080

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /health
    port: 6000
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /health
    port: 6000
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 3

env:
  - name: HOST
    value: "0.0.0.0"
  - name: PORT
    value: "6000"

nodeSelector: {}
tolerations: []
affinity: {}
