replicaCount: 1

image:
  repository: prizrakzamkov/system-info-api
  tag: "latest"
  pullPolicy: Always

environment: development
logLevel: DEBUG

features:
  metrics: "true"
  visits: "true"

service:
  type: NodePort
  port: 80
  targetPort: 6000
  nodePort: 30080

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

persistence:
  enabled: true
  size: 50Mi