apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-app-statefulset
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/PrizrakZamkov/DevOps-Core-Course-Prizrak.git
    targetRevision: main
    path: k8s/system-info-api
    helm:
      valueFiles:
        - values-statefulset.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: stateful
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
