{{- if and .Values.secret.enabled .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "system-info-api.secretName" . }}
  labels:
    {{- include "system-info-api.labels" . | nindent 4 }}
type: {{ .Values.secret.type }}
stringData:
  {{- range $key, $value := .Values.secret.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
